apiVersion: v1
kind: Service
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.repoName }}
spec:
  selector:
    app: ${{ values.repoName }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000