apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ parameters.repoName }}
  namespace: ${{ parameters.repoName }}
  labels:
    app: ${{ parameters.repoName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ parameters.repoName }}
  template:
    metadata:
      labels:
        app: ${{ parameters.repoName }}
    spec:
      containers:
        - name: app
          image: docker.io/guslopezc/${{ parameters.repoName }}:ci
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi