apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.repoName }}
spec:
  ingressClassName: kong
  rules:
    - host: ${{ values.repoName }}.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.repoName }}
                port:
                  name: http