apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: gusLopezC-DevOps/${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.repoName }}
    backstage.io/kubernetes-namespace: ${{ values.repoName }}
    backstage.io/techdocs-ref: url:https://github.com/gusLopezC-DevOps/${{ values.repoName }}/tree/main
spec:
  type: website
  lifecycle: production
  owner: group:default/${{ values.grupo }}