FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/job .

FROM gcr.io/distroless/static-debian12
COPY --from=build /app/job /job
ENTRYPOINT ["/job"]